### ISSUE TITLE
Error from example notebook `Quantinuum_arbitrary_angle_zz.ipynb`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#463]
See https://github.com/CQCL/pytket-quantinuum/actions/runs/9780854154/job/27003512164

```
Traceback (most recent call last):
  File "/home/runner/work/pytket-quantinuum/pytket-quantinuum/examples/Quantinuum_n56_ghz_state_fidelity.py", line 172, in <module>
    handles = qntm_backend_syntax_checker.process_circuits(
  File "/home/runner/work/pytket-quantinuum/pytket-quantinuum/pytket/extensions/quantinuum/backends/quantinuum.py", line 1025, in process_circuits
    quantinuum_circ = circuit_to_qasm_str(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pytket/qasm/qasm.py", line 1115, in circuit_to_qasm_str
    check_can_convert_circuit(circ, header, maxwidth)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pytket/qasm/qasm.py", line 1082, in check_can_convert_circuit
    raise QASMUnsupportedError(
pytket.qasm.qasm.QASMUnsupportedError: Circuit contains a classical register larger than 32: try setting the `maxwidth` parameter to a higher value.
```

**Comment by cqc-alec** [comment]
This now seems to be working.
